name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        include:
          - os: macos-latest
            test-command: ./test.sh
          - os: ubuntu-latest
            test-command: ./test.sh
          - os: windows-latest
            test-command: .\test.cmd

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: ${{ matrix.test-command }}
